name: notas
description: An application to save notes on your phone.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^8.0.0
  # Provider for handle the state
  provider: ^6.1.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Local cache
  hive: ^2.2.3
  # For OS-specific directory paths
  path_provider: ^2.1.0
  # Notifications
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Launcher app icon
  flutter_launcher_icons: ^0.14.0
  # Lint
  flutter_lints: ^5.0.0
  # Generated Hive adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/background.png" 
  adaptive_icon_foreground: "assets/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/